name: Close inactive pull requests
on:
  schedule:
    - cron: "30 1 * * *"
jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Awaiting response issues
        uses: actions/stale@v9
        with:
          days-before-pr-stale: 30
          days-before-pr-close: 5
          stale-pr-message: >
            This pull request has been marked as stale because it has been open for 30 days with no activity.
            It will be closed if no further activity occurs.
          close-pr-message: >
            This pull request has been closed because due to inactivity.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
